SharedGarden.Web/Controllers/GardenController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.JSInterop;
using Microsoft.AspNetCore.Mvc;
using SharedGarden.Web.Models;
using SharedGarden.Web.Services;
using System;
using System.Collections.Generic;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace SharedGarden.Web.Controllers
{
    public delegate UserModel DelegateGetCurrentUser();
    public class GardenController : Controller
    {
        IList<GardenModel> gardenList = new List<GardenModel>();
        IList<GardenModel> userGardens = new List<GardenModel>();
        public static DelegateGetCurrentUser delegateGetCurrentUser;
        [Authorize]
        public IActionResult Index()
        {

            gardenList = GardenServices.GetAllGardens();
            if (delegateGetCurrentUser != null )
                userGardens = delegateGetCurrentUser.Invoke().Id > 0 ? GardenServices.GetGardenByUserId(delegateGetCurrentUser.Invoke().Id) : new List<GardenModel>();

            ViewBag.AllGardensList = gardenList;
            ViewBag.UserGardenList = userGardens;

            return this.View();
        }
        [Authorize]
        public IActionResult GardenDetails(int id)
        {
            GardenModel garden = GardenServices.GetGardenById(id);
            ViewBag.Garden = garden;
            string address = garden.Address.Country + " " + garden.Address.PostalCode + " " + garden.Address.City + " " + garden.Address.Street;
            ViewBag.GardenAddress = address.Replace("\'", " ");
            return View();
        }


        #region AddGarden

        [Authorize]
        public IActionResult AddGarden()
        {
            return View();
        }
        
        public static void Test(string? result)
        {
            Console.WriteLine(result);
        }
        #endregion



    }
}

SharedGarden.Web/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;
using SharedGarden.Web.Models;
using SharedGarden.Web.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace SharedGarden.Web.Controllers
{
    public class ReservationController : Controller
    {
        IList<ReservationModel> allUserRes = new List<ReservationModel>();
        IList<ReservationModel> resAsOwner = new List<ReservationModel>();
        IList<ReservationModel> resAsClient = new List<ReservationModel>();
        public static DelegateGetCurrentUser delegateGetCurrentUser;
        UserModel currentUser = new UserModel { Id = -1 };

        public IActionResult Index()
        {
            if (delegateGetCurrentUser !=null)
            {
                currentUser = delegateGetCurrentUser.Invoke();
                allUserRes = currentUser.Id > 0 ? ReservationServices.GetReservationsByUserId(currentUser.Id) : new List<ReservationModel>();
                if(allUserRes.Count > 0)
                {
                    resAsOwner = allUserRes.Where(r => r.Garden.OwnerId == currentUser.Id).ToList<ReservationModel>();
                    resAsClient = allUserRes.Where(r => r.ClientId== currentUser.Id).ToList<ReservationModel>();
                }
            }
            ViewBag.ReservationAsOwner = resAsOwner;
            ViewBag.ReservationAsClient = resAsClient;
            return View();
        }
    }
}

SharedGarden.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shared Garden</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color:beige">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#77b300">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="home" asp-action="index">SharedGarden</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarsupportedcontent"
                        aria-expanded="false" aria-label="toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="home" asp-action="index">Home</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Garden" asp-action="index">Gardens</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Reservation" asp-action="index">Reservations</a>
                            </li>
                        }
                        @*<li 
                        class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Claims">Claims</a>
                        </li>*@
                    </ul>
                </div>
            </div>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a id="qsLogoutBtn" asp-controller="Account" asp-action="Logout">Logout</a></li>
                    }else
                    {
                        <li style="margin-left:50px" ><a id="qsLoginBtn" asp-controller="Account" asp-action="Login">Login</a></li >
                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - SharedGarden.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>